# Generated by Django 4.1.4 on 2022-12-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0002_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_name", models.CharField(max_length=250)),
                ("director", models.TextField()),
            ],
            options={
                "db_table": "movies",
            },
        ),
    ]
